# Dockerfile for Node-RED - pulls latest master code from git
# Use the node.js v0.10.36 engine
FROM node:0.10-slim
MAINTAINER kh.Slimi
 
# download latest stable node-red
RUN npm install -g grunt-cli
RUN git clone https://github.com/MADAR15/IoT-Modeler.git
RUN cd IoT-Modeler
RUN npm install
RUN grunt build
RUN node red.js
# use external storage for the user directory
VOLUME /root/.node-red

# expose port
EXPOSE 1880
 
# Set the default command to execute
# when creating a new container
#CMD /usr/local/bin/node-reds