# Dockerfile for Node-RED - pulls latest master code from git
# Use the node.js v0.10.36 engine
FROM node:0.12.7
MAINTAINER kh.Slimi
 
# download latest stable node-red
RUN npm install -g grunt-cli
RUN apt-get update
RUN apt-get install -y git build-essential
RUN apt-get install python -y
# docker build doesn't set env so node-gyp fails
ENV USER root
RUN git clone https://github.com/MADAR15/IoT-Modeler.git
WORKDIR "/IoT-Modeler"
RUN npm install
RUN grunt build
# use external storage for the user directory
VOLUME /root/.node-red

# expose port
EXPOSE 1880
CMD node red.js

# Set the default command to execute
# when creating a new container
#CMD /usr/local/bin/node-reds